services:
  tomcat-cve:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  struts2-s2-045:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  spring-webmvc:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
